easyadmin:
    resource: ../src/Module/**/*Controller.php
    type: easyadmin.routes

module.controllers:
    resource: ../src/Module/**/*Controller.php
    type: attribute

slack.controllers:
    resource: ../src/Infrastructure/Slack/Controller/*Controller.php
    type: attribute

ical.controllers:
    resource: ../src/Infrastructure/Ical/Controller/*Controller.php
    type: attribute