framework:
    secret: '%env(APP_SECRET)%'
    property_access: { enabled: true }
    session:
        handler_id: 'Symfony\Component\HttpFoundation\Session\Storage\Handler\PdoSessionHandler'
        cookie-samesite: strict
        cookie_lifetime: 604800 # 7 days
        gc_maxlifetime: 604800

when@test:
    framework:
        test: true
        session:
            storage_factory_id: session.storage.factory.mock_file
