twig:
    file_name_pattern: '*.twig'
    paths:
        'src/Module/Admin/template': 'AppAdmin'
    globals:
        profile_images_base_path: '%profile_images_base_path%'

when@test:
    twig:
        strict_variables: true
